print ("     MY 10th MARK LIST     ")
my_tamil = int (input("Enter Your Tamil Mark : "))
my_english = int (input("Enter Your English Mark : "))
my_maths = int (input("Enter Your Maths Mark : "))
my_science = int (input("Enter Your Science Mark : "))
my_social = int (input("Enter Your Social Mark : "))
my_total = (my_tamil+my_english+my_maths+my_science+my_social)
print("My Tamil Mark : ",my_tamil)
print("My English Mark : ",my_english)
print("My Maths Mark : ",my_maths)
print("My Science Mark : ",my_science)
print("My Social Mark : ",my_social)
print("My Total Mark : ",my_total)
