print ("     MY 12th MARK LIST     ")
my_tamil = int (input("Enter Your Tamil Mark : "))
my_english = int (input("Enter Your English Mark : "))
my_physics = int (input("Enter Your Physics Mark : "))
my_chemistry = int (input("Enter Your Chemistry Mark : "))
my_computer_science = int (input("Enter Computer Science Mark : "))
my_maths = int (input("Enter Your Maths Mark : "))
my_total = (my_tamil+my_english+my_maths+my_computer_science+my_physics+my_chemistry)
print("My Tamil Mark : ",my_tamil)
print("My English Mark : ",my_english)
print("My Physics Mark : ",my_physics)
print("My Chemistry Mark : ",my_chemistry)
print("My Computer Science Mark : ",my_computer_science)
print("My Maths Mark : ",my_maths)
print("My Total Mark : ",my_total)
