print ("                            BANK DETAILS")
name = input("Enter Your Name : ")
account_no = input("Enter Your Account Number : ")
ifsc_code = str (input("Enter Your IFSC Code : "))
email_id =  str (input("Enter Your Email ID : "))
mobile = int (input("Enter Your Mobile Number : "))
bank_balance = int (input("Enter Your Bank Balance : "))
print("My Name Is : ",name)
print("My Account Number Is : ",account_no)
print("My IFSC Code Is : ",ifsc_code)
print("My Email ID Is : ",email_id)
print("My Mobile Number Is : ",mobile)
print("My Bank Balace Is : ",bank_balance)
