print ("     MY FAMILY MEMBERS LIST     ")
my_name = input(("Enter Your Name : "))
my_father = input(("Enter Your Father Name : "))
my_mother = input(("Enter Your Mother Name : "))
my_brother = input(("Enter Your Brother Name : "))
print("My Name : ",my_name)
print("My Father Name : ",my_father)
print("My Mother Name : ",my_mother)
print("My Brother Name : ",my_brother)
